// Code generated by mongowrapper. DO NOT EDIT.
package tests

import (
	"context"
	"go.mongodb.org/mongo-driver/mongo"
)

func (s *usersRepository) AggregateToUserView(ctx context.Context, pipeline mongo.Pipeline, limit int) ([]*UserView, error) {
	if cursor, err := s.c.Aggregate(ctx, pipeline); err != nil {
		if err == mongo.ErrNoDocuments {
			return nil, nil
		} else {
			return nil, err
		}
	} else {
		records := make([]*UserView, 0, limit)
		for cursor.Next(ctx) {
			t := UserView{}
			err := cursor.Decode(&t)
			if err != nil {
				return records, err
			}
			records = append(records, &t)
		}
		return records, nil
	}
}
